# Generated by Django 5.2.5 on 2025-08-07 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage dans la navbar")),
            ],
            options={
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('nom_url', models.CharField(help_text="Nom de l'URL Django", max_length=100)),
                ('ordre', models.IntegerField(default=0, help_text='Ordre dans le groupe')),
                ('is_active', models.BooleanField(default=True)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages_list', to='configurations.groupepage')),
            ],
            options={
                'ordering': ['groupe', 'ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='AssociationUtilisateurGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('page_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.groupepage')),
            ],
            options={
                'unique_together': {('user', 'page_group')},
            },
        ),
        migrations.CreateModel(
            name='PageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('url_pattern', models.CharField(max_length=200)),
                ('nom_template', models.CharField(max_length=200)),
                ('ordre', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('show_in_navbar', models.BooleanField(default=True)),
                ('titre_page', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages_config', to='configurations.groupepage')),
            ],
            options={
                'ordering': ['groupe', 'ordre', 'nom'],
                'unique_together': {('groupe', 'ordre')},
            },
        ),
    ]
