# Generated by Django 5.2.5 on 2025-08-08 08:19

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('configurations', '0002_customgroup_groupmembership_customgroup_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupManagerGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Gestionnaire de groupes',
                'verbose_name_plural': '🔑 Gestionnaires de groupes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
