# Generated by Django 5.2.5 on 2025-08-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0005_alter_criteresnotation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notateur',
            name='nom_slug',
            field=models.CharField(blank=True, help_text="Nom original pour l'affichage", max_length=255),
        ),
        migrations.AddField(
            model_name='notateur',
            name='prenom_slug',
            field=models.CharField(blank=True, help_text="Prénom original pour l'affichage", max_length=255),
        ),
    ]
