# Generated by Django 5.2.5 on 2025-08-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0006_notateur_nom_slug_notateur_prenom_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='conducteur',
            name='nom_slug',
            field=models.CharField(blank=True, help_text="Nom original pour l'affichage", max_length=255),
        ),
        migrations.AddField(
            model_name='conducteur',
            name='prenom_slug',
            field=models.CharField(blank=True, help_text="Prénom original pour l'affichage", max_length=255),
        ),
    ]
